---
kind: pipeline
type: kubernetes
name: demo-develop
steps:
  # - name: demo-build
  #   image: node:14-alpine
  #   commands:
  #     - npm install
  #     - npm run build
  #     - cp src/sdk.js dist/demo/sdk.js
  - name: publish-nginx-gcr
    image: plugins/gcr
    settings:
      cache_from: ding4pro/demo/gtm/develop
      dockerfile: drone-ci/nginx.Dockerfile
      json_key:
        from_secret: gcr_credential
      registry: gcr.io
      repo: ding4pro/demo/gtm/develop
      tags:
        - latest
  - name: demo-helm
    image: pelotech/drone-helm3
    settings:
      api_server: https://10.40.13.240
      chart: ./drone-ci/helm
      kube_certificate:
        from_secret: ca
      kube_service_account:
        from_secret: account
      kube_token:
        from_secret: token
      mode: upgrade
      namespace: develop
      release: demo
      values_files: ./drone-ci/helm/develop.yaml
trigger:
  branch:
    - develop
    - main
  event:
    - push