gcr:
  host: gcr.io/
  project: ding4pro/

image: demo/gtm/develop

# port default listen 80
# env 額外的環境變數
deployment:
  - name: demo

# default port 80
# default targetPort 17000
# default selector is ${name}
# nodePort is develop local connect
service:
  - name: demo

ingressroute:
  - certResolver: cf
    name: demo
    domain: demo.4ding.xyz
    service: demo
ingressTCP:
